server:
  port: ${PORT:6001}
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jackson:
    serialization:
      indent_output: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  main:
    banner-mode: 'off'
